# Workflow removed

The workflow 'update_profile_art.yml' was removed from main per request. See backup branch if you need it:
https://github.com/BoyDeathMonsters/BoyDeathMonsters/tree/backup%2Ftoday-2026-08-15
